set -g mouse on


bind -n M-H resize-pane -L 2 # Alt + H	Resize left by 2
bind -n M-L resize-pane -R 2 # Alt + L	Resize right by 2
bind -n M-K resize-pane -U 2 # Alt + K	Resize up by 2
bind -n M-J resize-pane -D 2 # Alt + J	Resize down by 2
